services:
  - type: web
    name: book-marketplace-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://book-marketplace-backend.onrender.com/api
      - key: REACT_APP_SOCKET_URL
        value: https://book-marketplace-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
